version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
          - version-update:semver-major
    groups:
      npm-patch-and-minor:
        applies-to: version-updates
        patterns: ["*"]
        update-types:
          - patch
          - minor

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
          - version-update:semver-major
    groups:
      nuget-patch-and-minor:
        applies-to: version-updates
        patterns: ["*"]
        update-types:
          - patch
          - minor
