// Generates version-independent bridge modules for the Fable TypeScript runtime.
//
// Fable writes its runtime library to `src/generated/fable_modules/
// fable-library-ts.<version>/`, so a handwritten import of that path breaks on
// every Fable upgrade. After each Fable compilation, this script writes one
// re-exporting module per runtime module to `src/generated/fable-library/`, and
// handwritten TypeScript imports from there instead.
//
// The bridge re-exports the same runtime copy that Fable's own output imports,
// so runtime classes keep a single identity. The version is therefore read from
// the first-party generated imports rather than by picking a directory: stale
// `fable-library-ts.*` directories can survive an upgrade.
//
// This script runs as a post-fable step in scripts/Build.fsx.

open System.IO
open System.Text.RegularExpressions

module internal CommandLine =
    type Command =
        | GenerateBridge
        | RunSelfTest

    let parseArguments arguments =
        match arguments with
        | [] -> Ok GenerateBridge
        | [ "--self-test" ] -> Ok RunSelfTest
        | _ -> Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"

module internal Bridge =
    type BridgeError =
        | NoRuntimeImports
        | ConflictingVersions of versions: string list
        | RuntimeDirectoryMissing of path: string

    type BridgeModule = { Name: string; HasDefaultExport: bool }

    let bridgeDirectoryName = "fable-library"
    let fableModulesDirectoryName = "fable_modules"
    let runtimePackagePrefix = "fable-library-ts."

    let runtimeImportPattern =
        Regex($"{fableModulesDirectoryName}/{Regex.Escape runtimePackagePrefix}([^/\"']+)/")

    /// \b is a regex word boundary, not a backspace in this verbatim string.
    let defaultExportPattern = Regex(@"^export\s+default\b", RegexOptions.Multiline)

    // Excludes Fable's package output and this script's own output, relative to
    // src/generated.
    let isFirstPartySource (relativePath: string) =
        let topDirectory = relativePath.Split(Path.DirectorySeparatorChar)[0]

        topDirectory <> fableModulesDirectoryName && topDirectory <> bridgeDirectoryName

    let runtimeVersionsIn (source: string) =
        runtimeImportPattern.Matches(source) |> Seq.map _.Groups[1].Value |> Set.ofSeq

    let resolveVersion versions =
        match versions |> Set.toList with
        | [] -> Error NoRuntimeImports
        | [ version ] -> Ok version
        | several -> Error(ConflictingVersions several)

    let hasDefaultExport (source: string) = defaultExportPattern.IsMatch source

    let renderBridge version bridgeModule =
        let specifier =
            $"../{fableModulesDirectoryName}/{runtimePackagePrefix}{version}/{bridgeModule.Name}.ts"

        $"""// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.
export * from "{specifier}";
"""
        + if bridgeModule.HasDefaultExport then
              $"""export {{ default }} from "{specifier}";
"""
          else
              ""

    let errorMessage error =
        match error with
        | NoRuntimeImports ->
            "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
        | ConflictingVersions versions ->
            let versionList = versions |> String.concat ", "

            $"ERROR: generated code imports several Fable runtime versions (%s{versionList}). Delete src/generated and run the Fable target again."
        | RuntimeDirectoryMissing path -> $"ERROR: Fable runtime directory %s{path} is missing."

module internal FileSystem =
    let scanRuntimeVersions generatedRoot =
        Directory.EnumerateFiles(generatedRoot, "*.ts", SearchOption.AllDirectories)
        |> Seq.filter (fun path -> Path.GetRelativePath(generatedRoot, path) |> Bridge.isFirstPartySource)
        |> Seq.map (File.ReadAllText >> Bridge.runtimeVersionsIn)
        |> Set.unionMany

    let runtimeDirectory generatedRoot version =
        let path =
            Path.Combine(generatedRoot, Bridge.fableModulesDirectoryName, Bridge.runtimePackagePrefix + version)

        if Directory.Exists path then
            Ok path
        else
            Error(Bridge.RuntimeDirectoryMissing path)

    let readBridgeModules runtimePath =
        Directory.EnumerateFiles(runtimePath, "*.ts", SearchOption.TopDirectoryOnly)
        |> Seq.map (fun path ->
            ({
                Name = Path.GetFileNameWithoutExtension path
                HasDefaultExport = path |> File.ReadAllText |> Bridge.hasDefaultExport
            }
            : Bridge.BridgeModule))
        |> Seq.sortBy _.Name
        |> List.ofSeq

    let writeBridge generatedRoot version (bridgeModules: Bridge.BridgeModule list) =
        let bridgeRoot = Path.Combine(generatedRoot, Bridge.bridgeDirectoryName)

        if Directory.Exists bridgeRoot then
            Directory.Delete(bridgeRoot, true)

        Directory.CreateDirectory bridgeRoot |> ignore

        for bridgeModule in bridgeModules do
            File.WriteAllText(
                Path.Combine(bridgeRoot, bridgeModule.Name + ".ts"),
                Bridge.renderBridge version bridgeModule
            )

    let generate generatedRoot =
        if not (Directory.Exists generatedRoot) then
            Error Bridge.NoRuntimeImports
        else
            scanRuntimeVersions generatedRoot
            |> Bridge.resolveVersion
            |> Result.bind (fun version ->
                runtimeDirectory generatedRoot version
                |> Result.map (fun runtimePath -> version, readBridgeModules runtimePath))

module internal SelfTest =
    let runSelfTest () =
        let assertEqual name expected actual =
            if expected <> actual then
                failwith (sprintf "Self-test failed: %s. Expected %A, got %A." name expected actual)

        let usage = Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"
        assertEqual "no arguments generate the bridge" (Ok CommandLine.GenerateBridge) (CommandLine.parseArguments [])
        assertEqual "self-test arguments" (Ok CommandLine.RunSelfTest) (CommandLine.parseArguments [ "--self-test" ])
        assertEqual "unknown arguments fail" usage (CommandLine.parseArguments [ "--unknown" ])
        assertEqual "extra arguments fail" usage (CommandLine.parseArguments [ "--self-test"; "--self-test" ])

        assertEqual
            "first-party output is scanned"
            true
            (Bridge.isFirstPartySource (Path.Combine("ViewModel", "Scene.ts")))

        assertEqual
            "Fable's package output is not scanned"
            false
            (Bridge.isFirstPartySource (Path.Combine("fable_modules", "fable-library-ts.5.1.0", "List.ts")))

        assertEqual
            "the bridge's own output is not scanned"
            false
            (Bridge.isFirstPartySource (Path.Combine("fable-library", "List.ts")))

        assertEqual
            "a first-party directory merely containing the bridge name is scanned"
            true
            (Bridge.isFirstPartySource (Path.Combine("Persistence", "fable-library.ts")))

        let firstPartySource =
            """import { int32 } from "./fable_modules/fable-library-ts.5.1.0/Int32.ts";
import { Record } from "../fable_modules/fable-library-ts.5.1.0/Types.ts";
import { Decoder } from "./fable_modules/Thoth.Json.Core.0.9.1/Types.fs.ts";
"""

        assertEqual
            "runtime imports yield their version and other packages are ignored"
            (Set [ "5.1.0" ])
            (Bridge.runtimeVersionsIn firstPartySource)

        assertEqual
            "pre-release versions are captured whole"
            (Set [ "5.0.0-rc.2" ])
            (Bridge.runtimeVersionsIn """import { a } from "./fable_modules/fable-library-ts.5.0.0-rc.2/A.ts";""")

        assertEqual "a single version resolves" (Ok "5.1.0") (Bridge.resolveVersion (Set [ "5.1.0" ]))
        assertEqual "no versions fail" (Error Bridge.NoRuntimeImports) (Bridge.resolveVersion Set.empty)

        assertEqual
            "several versions fail and are all reported"
            (Error(Bridge.ConflictingVersions [ "5.1.0"; "5.20.0" ]))
            (Bridge.resolveVersion (Set [ "5.20.0"; "5.1.0" ]))

        assertEqual "a default export is detected" true (Bridge.hasDefaultExport "class A {}\nexport default A;\n")

        assertEqual
            "a default function export is detected"
            true
            (Bridge.hasDefaultExport "export default function f() {}\n")

        assertEqual
            "an identifier beginning with default is not a default export"
            false
            (Bridge.hasDefaultExport "export defaultValue;\n")

        assertEqual
            "named exports alone are not default exports"
            false
            (Bridge.hasDefaultExport "export function f() {}\nexport const defaultValue = 1;\n")

        assertEqual
            "a commented-out default export is not detected"
            false
            (Bridge.hasDefaultExport "// export default A;\n")

        assertEqual
            "a module without a default export re-exports its named exports"
            ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
             + "export * from \"../fable_modules/fable-library-ts.5.1.0/List.ts\";\n")
            (Bridge.renderBridge "5.1.0" { Name = "List"; HasDefaultExport = false })

        assertEqual
            "a module with a default export also re-exports the default"
            ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
             + "export * from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n"
             + "export { default } from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n")
            (Bridge.renderBridge "5.20.0" { Name = "Date"; HasDefaultExport = true })

        assertEqual
            "missing runtime imports explain how to recover"
            "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
            (Bridge.errorMessage Bridge.NoRuntimeImports)

        assertEqual
            "conflicting versions are listed and explain how to recover"
            "ERROR: generated code imports several Fable runtime versions (5.1.0, 5.20.0). Delete src/generated and run the Fable target again."
            (Bridge.errorMessage (Bridge.ConflictingVersions [ "5.1.0"; "5.20.0" ]))

        assertEqual
            "a missing runtime directory is named"
            "ERROR: Fable runtime directory /missing/dir is missing."
            (Bridge.errorMessage (Bridge.RuntimeDirectoryMissing "/missing/dir"))

        let root =
            Path.Combine(Path.GetTempPath(), "fable-bridge-self-test-" + string (System.Guid.NewGuid()))

        let write relativePath (content: string) =
            let path = Path.Combine(Array.append [| root |] relativePath)
            Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
            File.WriteAllText(path, content)

        let runtimeImport version =
            $"import {{ a }} from \"./fable_modules/fable-library-ts.%s{version}/List.ts\";\n"

        try
            assertEqual "a missing generated root fails" (Error Bridge.NoRuntimeImports) (FileSystem.generate root)

            write [| "Model.ts" |] "export const x = 1;\n"

            assertEqual
                "a tree without runtime imports fails"
                (Error Bridge.NoRuntimeImports)
                (FileSystem.generate root)

            write [| "Model.ts" |] (runtimeImport "5.1.0")
            let missingRuntime = Path.Combine(root, "fable_modules", "fable-library-ts.5.1.0")

            assertEqual
                "an imported runtime directory that does not exist fails"
                (Error(Bridge.RuntimeDirectoryMissing missingRuntime))
                (FileSystem.generate root)

            write [| "fable_modules"; "fable-library-ts.5.1.0"; "List.ts" |] "export function f() {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "Date.ts" |] "export default class D {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "lib"; "big.ts" |] "export default 1;\n"
            write [| "fable_modules"; "fable-library-ts.9.9.9"; "List.ts" |] "export function g() {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "Stale.ts" |] (runtimeImport "9.9.9")
            write [| "fable-library"; "Removed.ts" |] (runtimeImport "9.9.9")

            let expectedModules: Bridge.BridgeModule list = [
                { Name = "Date"; HasDefaultExport = true }
                { Name = "List"; HasDefaultExport = false }
                { Name = "Stale"; HasDefaultExport = false }
            ]

            assertEqual
                "only first-party imports choose the version, and only top-level runtime modules are bridged"
                (Ok("5.1.0", expectedModules))
                (FileSystem.generate root)

            FileSystem.writeBridge root "5.1.0" expectedModules

            assertEqual
                "the bridge directory is recreated, removing stale modules"
                [ "Date.ts"; "List.ts"; "Stale.ts" ]
                (Directory.GetFiles(Path.Combine(root, "fable-library"))
                 |> Array.map Path.GetFileName
                 |> Array.sort
                 |> List.ofArray)

            assertEqual
                "written bridges match the rendered contents"
                (Bridge.renderBridge "5.1.0" { Name = "Date"; HasDefaultExport = true })
                (File.ReadAllText(Path.Combine(root, "fable-library", "Date.ts")))

            write [| "Other.ts" |] (runtimeImport "9.9.9")

            assertEqual
                "first-party imports of two versions fail"
                (Error(Bridge.ConflictingVersions [ "5.1.0"; "9.9.9" ]))
                (FileSystem.generate root)
        finally
            if Directory.Exists root then
                Directory.Delete(root, true)

        printfn "Self-test: passed."

// --- Top-level I/O and control flow ---

let scriptArgs = fsi.CommandLineArgs |> Array.skip 1

match CommandLine.parseArguments (scriptArgs |> Array.toList) with
| Error usage ->
    eprintfn "%s" usage
    exit 2
| Ok CommandLine.RunSelfTest -> SelfTest.runSelfTest ()
| Ok CommandLine.GenerateBridge ->
    let repoRoot = Path.GetDirectoryName(Path.GetFullPath(__SOURCE_DIRECTORY__))
    let generatedRoot = Path.Combine(repoRoot, "src", "generated")

    match FileSystem.generate generatedRoot with
    | Error error ->
        eprintfn "%s" (Bridge.errorMessage error)
        exit 1
    | Ok(version, bridgeModules) ->
        FileSystem.writeBridge generatedRoot version bridgeModules

        printfn
            $"GenerateFableLibraryBridge: wrote %d{bridgeModules.Length} bridge module(s) for fable-library-ts %s{version}."
