// Generates version-independent bridge modules for the Fable TypeScript runtime.
//
// Fable writes its runtime library to `src/generated/fable_modules/
// fable-library-ts.<version>/`, so a handwritten import of that path breaks on
// every Fable upgrade. After each Fable compilation, this script writes one
// re-exporting module per runtime module to `src/generated/fable-library/`, and
// handwritten TypeScript imports from there instead.
//
// The bridge re-exports the same runtime copy that Fable's own output imports,
// so runtime classes keep a single identity. The version is therefore read from
// the first-party generated imports rather than by picking a directory: stale
// `fable-library-ts.*` directories can survive an upgrade.
//
// This script runs as a post-fable step in scripts/Build.fsx.

open System.ComponentModel
open System.Diagnostics
open System.IO
open System.Text.Json
open System.Text.RegularExpressions

module internal CommandLine =
    type Command =
        | GenerateBridge
        | RunSelfTest

    let parseArguments arguments =
        match arguments with
        | [] -> Ok GenerateBridge
        | [ "--self-test" ] -> Ok RunSelfTest
        | _ -> Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"

module internal Bridge =
    type BridgeError =
        | NoRuntimeImports
        | ConflictingVersions of versions: string list
        | RuntimeDirectoryMissing of path: string

    type BridgeModule = { Name: string; HasDefaultExport: bool }

    let bridgeDirectoryName = "fable-library"
    let fableModulesDirectoryName = "fable_modules"
    let runtimePackagePrefix = "fable-library-ts."

    let runtimeImportPattern =
        Regex($"{fableModulesDirectoryName}/{Regex.Escape runtimePackagePrefix}([^/\"']+)/")

    // Excludes Fable's package output and this script's own output, relative to
    // src/generated.
    let isFirstPartySource (relativePath: string) =
        let topDirectory = relativePath.Split(Path.DirectorySeparatorChar)[0]

        topDirectory <> fableModulesDirectoryName && topDirectory <> bridgeDirectoryName

    let runtimeVersionsIn (source: string) =
        runtimeImportPattern.Matches(source) |> Seq.map _.Groups[1].Value |> Set.ofSeq

    let resolveVersion versions =
        match versions |> Set.toList with
        | [] -> Error NoRuntimeImports
        | [ version ] -> Ok version
        | several -> Error(ConflictingVersions several)

    let renderBridge version bridgeModule =
        let specifier =
            $"../{fableModulesDirectoryName}/{runtimePackagePrefix}{version}/{bridgeModule.Name}.ts"

        let defaultExport =
            $"""export {{ default }} from "{specifier}";
"""

        $$"""// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.
export * from "{{specifier}}";
{{if bridgeModule.HasDefaultExport then defaultExport else ""}}"""

    let errorMessage error =
        match error with
        | NoRuntimeImports ->
            "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
        | ConflictingVersions versions ->
            let versionList = versions |> String.concat ", "

            $"ERROR: generated code imports several Fable runtime versions (%s{versionList}). Delete src/generated and run the Fable target again."
        | RuntimeDirectoryMissing path -> $"ERROR: Fable runtime directory %s{path} is missing."

module internal TypeScript =
    open Bridge

    type ModuleSource = { Name: string; Source: string }

    type ParserField =
        | ModuleName
        | DefaultExport

    type ParserError =
        | MalformedJson
        | ExpectedArray
        | InvalidModuleCount
        | ExpectedObject of moduleName: string
        | MissingField of moduleName: string * field: ParserField
        | WrongFieldType of moduleName: string * field: ParserField
        | NameMismatch of expected: string * actual: string

    let private fieldName =
        function
        | ModuleName -> "Name"
        | DefaultExport -> "HasDefaultExport"

    let errorMessage error =
        let invalidResults detail =
            $"ERROR: TypeScript parser returned invalid JSON results: {detail}"

        match error with
        | MalformedJson -> invalidResults "malformed JSON."
        | ExpectedArray -> invalidResults "expected an array."
        | InvalidModuleCount -> "ERROR: TypeScript parser returned an invalid module count."
        | ExpectedObject name -> invalidResults $"module '{name}' must be an object."
        | MissingField(name, field) -> invalidResults $"module '{name}' is missing '{fieldName field}'."
        | WrongFieldType(name, field) ->
            let expectedType =
                match field with
                | ModuleName -> "string"
                | DefaultExport -> "boolean"

            invalidResults $"module '{name}' field '{fieldName field}' must be a {expectedType}."
        | NameMismatch(expected, actual) -> invalidResults $"expected module '{expected}', got '{actual}'."

    // Use the project's installed compiler, with one stdin batch rather than
    // command-line source arguments or a process per runtime module.
    let private parserScript =
        """
const sources = JSON.parse(require("node:fs").readFileSync(0, "utf8"));
const ts = require("typescript");
const results = sources.map(({ Name, Source }) => {
   const file = ts.createSourceFile(Name + ".ts", Source, ts.ScriptTarget.Latest, false, ts.ScriptKind.TS);
   const HasDefaultExport = file.statements.some(statement =>
       (ts.isExportAssignment(statement) && !statement.isExportEquals) ||
       (ts.canHaveModifiers(statement) &&
           ts.getModifiers(statement)?.some(modifier => modifier.kind === ts.SyntaxKind.DefaultKeyword)) ||
       (ts.isExportDeclaration(statement) && !statement.isTypeOnly &&
           statement.exportClause &&
           ((ts.isNamedExports(statement.exportClause) &&
               statement.exportClause.elements.some(specifier => !specifier.isTypeOnly && specifier.name.text === "default")) ||
            (ts.isNamespaceExport(statement.exportClause) && statement.exportClause.name.text === "default")))
   );
   return { Name, HasDefaultExport };
});
process.stdout.write(JSON.stringify(results));
"""

    let private parseDocument (output: string) =
        try
            JsonDocument.Parse output |> Ok
        with :? JsonException ->
            Error MalformedJson

    let private readField name field (result: JsonElement) =
        match result.TryGetProperty(fieldName field) with
        | false, _ -> Error(MissingField(name, field))
        | true, value ->
            match field, value.ValueKind with
            | ModuleName, JsonValueKind.String
            | DefaultExport, JsonValueKind.True
            | DefaultExport, JsonValueKind.False -> Ok value
            | _ -> Error(WrongFieldType(name, field))

    let private decodeModule (source: ModuleSource) (result: JsonElement) =
        if result.ValueKind <> JsonValueKind.Object then
            Error(ExpectedObject source.Name)
        else
            result
            |> readField source.Name ModuleName
            |> Result.bind (fun name ->
                let actualName = name.GetString()

                if actualName <> source.Name then
                    Error(NameMismatch(source.Name, actualName))
                else
                    result
                    |> readField source.Name DefaultExport
                    |> Result.map (fun classification -> {
                        Name = source.Name
                        HasDefaultExport = classification.GetBoolean()
                    }))

    let decodeResults (sources: ModuleSource array) (output: string) =
        output
        |> parseDocument
        |> Result.bind (fun parsed ->
            use document = parsed
            let root = document.RootElement

            if root.ValueKind <> JsonValueKind.Array then
                Error ExpectedArray
            elif root.GetArrayLength() <> sources.Length then
                Error InvalidModuleCount
            else
                let results =
                    root.EnumerateArray() |> Seq.toArray |> Array.map2 decodeModule sources

                Array.foldBack
                    (fun result accumulated ->
                        result
                        |> Result.bind (fun bridgeModule ->
                            accumulated |> Result.map (fun rest -> bridgeModule :: rest)))
                    results
                    (Ok [])
                |> Result.map List.toArray)
        |> Result.mapError errorMessage

    let parseSources sources =
        try
            let startInfo = ProcessStartInfo "node"
            startInfo.WorkingDirectory <- Path.GetDirectoryName(Path.GetFullPath(__SOURCE_DIRECTORY__))
            startInfo.UseShellExecute <- false
            startInfo.RedirectStandardInput <- true
            startInfo.RedirectStandardOutput <- true
            startInfo.RedirectStandardError <- true
            startInfo.ArgumentList.Add "-e"
            startInfo.ArgumentList.Add parserScript
            use parser = Process.Start startInfo
            let output = parser.StandardOutput.ReadToEndAsync()
            let errors = parser.StandardError.ReadToEndAsync()

            let input =
                sources
                |> Array.map (fun source -> dict [ "Name", source.Name; "Source", source.Source ])
                |> JsonSerializer.Serialize

            parser.StandardInput.Write input
            parser.StandardInput.Close()
            parser.WaitForExit()
            let output = output.GetAwaiter().GetResult()
            let errors = errors.GetAwaiter().GetResult()

            if parser.ExitCode <> 0 then
                Error $"ERROR: TypeScript parser failed (exit {parser.ExitCode}): {errors.Trim()}"
            else
                output |> decodeResults sources
        with
        | :? Win32Exception as error -> Error $"ERROR: could not run the TypeScript parser: {error.Message}"
        | :? IOException as error -> Error $"ERROR: could not run the TypeScript parser: {error.Message}"

module internal FileSystem =
    open Bridge
    open TypeScript

    let scanRuntimeVersions generatedRoot =
        Directory.EnumerateFiles(generatedRoot, "*.ts", SearchOption.AllDirectories)
        |> Seq.filter (fun path -> Path.GetRelativePath(generatedRoot, path) |> Bridge.isFirstPartySource)
        |> Seq.map (File.ReadAllText >> Bridge.runtimeVersionsIn)
        |> Set.unionMany

    let runtimeDirectory generatedRoot version =
        let path =
            Path.Combine(generatedRoot, Bridge.fableModulesDirectoryName, Bridge.runtimePackagePrefix + version)

        if Directory.Exists path then
            Ok path
        else
            Error(Bridge.RuntimeDirectoryMissing path)

    let readBridgeModules runtimePath =
        Directory.EnumerateFiles(runtimePath, "*.ts", SearchOption.TopDirectoryOnly)
        |> Seq.map (fun path -> {
            Name = Path.GetFileNameWithoutExtension path
            Source = File.ReadAllText path
        })
        |> Seq.sortBy _.Name

    let writeBridgeModules generatedRoot version (bridgeModules: BridgeModule seq) =
        let bridgeRoot = Path.Combine(generatedRoot, Bridge.bridgeDirectoryName)

        if Directory.Exists bridgeRoot then
            let recursive = true
            Directory.Delete(bridgeRoot, recursive)

        Directory.CreateDirectory bridgeRoot |> ignore

        for bridgeModule in bridgeModules do
            File.WriteAllText(
                Path.Combine(bridgeRoot, bridgeModule.Name + ".ts"),
                Bridge.renderBridge version bridgeModule
            )

    let readBridgePlan generatedRoot =
        if not (Directory.Exists generatedRoot) then
            Error Bridge.NoRuntimeImports
        else
            scanRuntimeVersions generatedRoot
            |> Bridge.resolveVersion
            |> Result.bind (fun version ->
                runtimeDirectory generatedRoot version
                |> Result.map (fun runtimePath -> version, readBridgeModules runtimePath))

module internal SelfTest =
    let runSelfTest () =
        let assertEqual name expected actual =
            if expected <> actual then
                failwith (sprintf "Self-test failed: %s. Expected %A, got %A." name expected actual)

        let usage = Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"
        assertEqual "no arguments generate the bridge" (Ok CommandLine.GenerateBridge) (CommandLine.parseArguments [])
        assertEqual "self-test arguments" (Ok CommandLine.RunSelfTest) (CommandLine.parseArguments [ "--self-test" ])
        assertEqual "unknown arguments fail" usage (CommandLine.parseArguments [ "--unknown" ])
        assertEqual "extra arguments fail" usage (CommandLine.parseArguments [ "--self-test"; "--self-test" ])

        assertEqual
            "first-party output is scanned"
            true
            (Bridge.isFirstPartySource (Path.Combine("ViewModel", "Scene.ts")))

        assertEqual
            "Fable's package output is not scanned"
            false
            (Bridge.isFirstPartySource (Path.Combine("fable_modules", "fable-library-ts.5.1.0", "List.ts")))

        assertEqual
            "the bridge's own output is not scanned"
            false
            (Bridge.isFirstPartySource (Path.Combine("fable-library", "List.ts")))

        assertEqual
            "a first-party directory merely containing the bridge name is scanned"
            true
            (Bridge.isFirstPartySource (Path.Combine("Persistence", "fable-library.ts")))

        let firstPartySource =
            """import { int32 } from "./fable_modules/fable-library-ts.5.1.0/Int32.ts";
import { Record } from "../fable_modules/fable-library-ts.5.1.0/Types.ts";
import { Decoder } from "./fable_modules/Thoth.Json.Core.0.9.1/Types.fs.ts";
"""

        assertEqual
            "runtime imports yield their version and other packages are ignored"
            (Set [ "5.1.0" ])
            (Bridge.runtimeVersionsIn firstPartySource)

        assertEqual
            "pre-release versions are captured whole"
            (Set [ "5.0.0-rc.2" ])
            (Bridge.runtimeVersionsIn """import { a } from "./fable_modules/fable-library-ts.5.0.0-rc.2/A.ts";""")

        assertEqual "a single version resolves" (Ok "5.1.0") (Bridge.resolveVersion (Set [ "5.1.0" ]))
        assertEqual "no versions fail" (Error Bridge.NoRuntimeImports) (Bridge.resolveVersion Set.empty)

        assertEqual
            "several versions fail and are all reported"
            (Error(Bridge.ConflictingVersions [ "5.1.0"; "5.20.0" ]))
            (Bridge.resolveVersion (Set [ "5.20.0"; "5.1.0" ]))

        let parserSources: TypeScript.ModuleSource array = [|
            { Name = "Assignment"; Source = "class A {}\nexport default A;\n" }
            { Name = "Function"; Source = "export default function f() {}\n" }
            { Name = "DefaultValue"; Source = "export defaultValue;\n" }
            {
                Name = "Named"
                Source = "export function f() {}\nexport const defaultValue = 1;\n"
            }
            { Name = "LineComment"; Source = "// export default A;\n" }
            { Name = "BlockComment"; Source = "/*\nexport default A;\n*/\n" }
            {
                Name = "AfterComment"
                Source = "/*\nexport default A;\n*/\nexport default class B {}\n"
            }
            { Name = "ExportEquals"; Source = "class A {}\nexport = A;\n" }
            {
                Name = "ReExport"
                Source = "export { value as default } from './Other.ts';\n"
            }
            {
                Name = "NamespaceDefault"
                Source = "export * as default from './Other.ts';\n"
            }
            {
                Name = "TypeOnlyNamespaceDefault"
                Source = "export type * as default from './Other.ts';\n"
            }
        |]

        let expectedParserModules: Bridge.BridgeModule array = [|
            { Name = "Assignment"; HasDefaultExport = true }
            { Name = "Function"; HasDefaultExport = true }
            { Name = "DefaultValue"; HasDefaultExport = false }
            { Name = "Named"; HasDefaultExport = false }
            { Name = "LineComment"; HasDefaultExport = false }
            { Name = "BlockComment"; HasDefaultExport = false }
            { Name = "AfterComment"; HasDefaultExport = true }
            { Name = "ExportEquals"; HasDefaultExport = false }
            { Name = "ReExport"; HasDefaultExport = true }
            { Name = "NamespaceDefault"; HasDefaultExport = true }
            { Name = "TypeOnlyNamespaceDefault"; HasDefaultExport = false }
        |]

        assertEqual
            "compiler results preserve each module's name and default-export classification across a batch"
            (Ok expectedParserModules)
            (TypeScript.parseSources parserSources)

        assertEqual
            "an incomplete parser response fails instead of silently omitting modules"
            (Error "ERROR: TypeScript parser returned an invalid module count.")
            (TypeScript.decodeResults parserSources "[]")

        let invalidParserResults = [
            "malformed parser output fails",
            "not JSON",
            "ERROR: TypeScript parser returned invalid JSON results: malformed JSON."
            "a non-array response fails",
            "{}",
            "ERROR: TypeScript parser returned invalid JSON results: expected an array."
            "a non-object module fails",
            "[null]",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' must be an object."
            "a missing name fails",
            """[{"HasDefaultExport":true}]""",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' is missing 'Name'."
            "a missing classification fails",
            """[{"Name":"Assignment"}]""",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' is missing 'HasDefaultExport'."
            "a non-string name fails",
            """[{"Name":1,"HasDefaultExport":true}]""",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' field 'Name' must be a string."
            "a null name fails",
            """[{"Name":null,"HasDefaultExport":true}]""",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' field 'Name' must be a string."
            "a non-boolean classification fails",
            """[{"Name":"Assignment","HasDefaultExport":"true"}]""",
            "ERROR: TypeScript parser returned invalid JSON results: module 'Assignment' field 'HasDefaultExport' must be a boolean."
            "misassociated parser results fail",
            """[{"Name":"Other","HasDefaultExport":true}]""",
            "ERROR: TypeScript parser returned invalid JSON results: expected module 'Assignment', got 'Other'."
        ]

        for name, output, message in invalidParserResults do
            assertEqual name (Error message) (TypeScript.decodeResults [| parserSources[0] |] output)

        assertEqual "an empty parser batch succeeds" (Ok [||]) (TypeScript.parseSources [||])
        assertEqual "an empty response matches an empty batch" (Ok [||]) (TypeScript.decodeResults [||] "[]")

        assertEqual
            "extra parser modules fail"
            (Error "ERROR: TypeScript parser returned an invalid module count.")
            (TypeScript.decodeResults [||] """[{"Name":"Other","HasDefaultExport":true}]""")

        assertEqual
            "a module without a default export re-exports its named exports"
            ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
             + "export * from \"../fable_modules/fable-library-ts.5.1.0/List.ts\";\n")
            (Bridge.renderBridge "5.1.0" { Name = "List"; HasDefaultExport = false })

        assertEqual
            "a module with a default export also re-exports the default"
            ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
             + "export * from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n"
             + "export { default } from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n")
            (Bridge.renderBridge "5.20.0" { Name = "Date"; HasDefaultExport = true })

        assertEqual
            "missing runtime imports explain how to recover"
            "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
            (Bridge.errorMessage Bridge.NoRuntimeImports)

        assertEqual
            "conflicting versions are listed and explain how to recover"
            "ERROR: generated code imports several Fable runtime versions (5.1.0, 5.20.0). Delete src/generated and run the Fable target again."
            (Bridge.errorMessage (Bridge.ConflictingVersions [ "5.1.0"; "5.20.0" ]))

        assertEqual
            "a missing runtime directory is named"
            "ERROR: Fable runtime directory /missing/dir is missing."
            (Bridge.errorMessage (Bridge.RuntimeDirectoryMissing "/missing/dir"))

        let root =
            Path.Combine(Path.GetTempPath(), "fable-bridge-self-test-" + string (System.Guid.NewGuid()))

        let write (relativePath: string array) (content: string) =
            let path = Path.Combine(root, Path.Combine relativePath)
            Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
            File.WriteAllText(path, content)

        let runtimeImport version =
            $"import {{ a }} from \"./fable_modules/fable-library-ts.%s{version}/List.ts\";\n"

        try
            assertEqual
                "a missing generated root fails"
                (Error Bridge.NoRuntimeImports)
                (FileSystem.readBridgePlan root)

            write [| "Model.ts" |] "export const x = 1;\n"

            assertEqual
                "a tree without runtime imports fails"
                (Error Bridge.NoRuntimeImports)
                (FileSystem.readBridgePlan root)

            write [| "Model.ts" |] (runtimeImport "5.1.0")
            let missingRuntime = Path.Combine(root, "fable_modules", "fable-library-ts.5.1.0")

            assertEqual
                "an imported runtime directory that does not exist fails"
                (Error(Bridge.RuntimeDirectoryMissing missingRuntime))
                (FileSystem.readBridgePlan root)

            write [| "fable_modules"; "fable-library-ts.5.1.0"; "List.ts" |] "export function f() {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "Date.ts" |] "export default class D {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "Commented.ts" |] "/*\nexport default A;\n*/\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "lib"; "big.ts" |] "export default 1;\n"
            write [| "fable_modules"; "fable-library-ts.9.9.9"; "List.ts" |] "export function g() {}\n"
            write [| "fable_modules"; "fable-library-ts.5.1.0"; "Stale.ts" |] (runtimeImport "9.9.9")
            write [| "fable-library"; "Removed.ts" |] (runtimeImport "9.9.9")

            let expectedModules: Bridge.BridgeModule array = [|
                { Name = "Commented"; HasDefaultExport = false }
                { Name = "Date"; HasDefaultExport = true }
                { Name = "List"; HasDefaultExport = false }
                { Name = "Stale"; HasDefaultExport = false }
            |]

            let plan =
                FileSystem.readBridgePlan root
                |> Result.mapError Bridge.errorMessage
                |> Result.bind (fun (version, sources) ->
                    sources
                    |> Seq.toArray
                    |> TypeScript.parseSources
                    |> Result.map (fun bridgeModules -> version, bridgeModules))

            assertEqual
                "only first-party imports choose the version, and only top-level runtime modules are bridged"
                (Ok("5.1.0", expectedModules))
                plan

            match plan with
            | Ok(version, bridgeModules) -> FileSystem.writeBridgeModules root version bridgeModules
            | Error message -> failwith message

            assertEqual
                "the bridge directory is recreated, removing stale modules"
                [ "Commented.ts"; "Date.ts"; "List.ts"; "Stale.ts" ]
                (Directory.GetFiles(Path.Combine(root, "fable-library"))
                 |> Array.map Path.GetFileName
                 |> Array.sort
                 |> List.ofArray)

            assertEqual
                "written bridges match the rendered contents"
                ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
                 + "export * from \"../fable_modules/fable-library-ts.5.1.0/Date.ts\";\n"
                 + "export { default } from \"../fable_modules/fable-library-ts.5.1.0/Date.ts\";\n")
                (File.ReadAllText(Path.Combine(root, "fable-library", "Date.ts")))

            assertEqual
                "a commented-out default export produces only a named-export bridge"
                ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
                 + "export * from \"../fable_modules/fable-library-ts.5.1.0/Commented.ts\";\n")
                (File.ReadAllText(Path.Combine(root, "fable-library", "Commented.ts")))

            write [| "Other.ts" |] (runtimeImport "9.9.9")

            assertEqual
                "first-party imports of two versions fail"
                (Error(Bridge.ConflictingVersions [ "5.1.0"; "9.9.9" ]))
                (FileSystem.readBridgePlan root)
        finally
            if Directory.Exists root then
                let recursive = true
                Directory.Delete(root, recursive)

        assertEqual "self-test fixtures are deleted" false (Directory.Exists root)

        printfn "Self-test: passed."

// --- Top-level I/O and control flow ---

let scriptArgs = fsi.CommandLineArgs |> Array.skip 1

match CommandLine.parseArguments (scriptArgs |> Array.toList) with
| Error usage ->
    eprintfn "%s" usage
    exit 2
| Ok CommandLine.RunSelfTest -> SelfTest.runSelfTest ()
| Ok CommandLine.GenerateBridge ->
    let repoRoot = Path.GetDirectoryName(Path.GetFullPath(__SOURCE_DIRECTORY__))
    let generatedRoot = Path.Combine(repoRoot, "src", "generated")

    let plan =
        FileSystem.readBridgePlan generatedRoot
        |> Result.mapError Bridge.errorMessage
        |> Result.bind (fun (version, sources) ->
            sources
            |> Seq.toArray
            |> TypeScript.parseSources
            |> Result.map (fun bridgeModules -> version, bridgeModules))

    match plan with
    | Error message ->
        eprintfn "%s" message
        exit 1
    | Ok(version, bridgeModules) ->
        FileSystem.writeBridgeModules generatedRoot version bridgeModules

        printfn
            $"GenerateFableLibraryBridge: wrote %d{bridgeModules.Length} bridge module(s) for fable-library-ts %s{version}."
