// Generates version-independent bridge modules for the Fable TypeScript runtime.
//
// Fable writes its runtime library to `src/generated/fable_modules/
// fable-library-ts.<version>/`, so a handwritten import of that path breaks on
// every Fable upgrade. After each Fable compilation, this script writes one
// re-exporting module per runtime module to `src/generated/fable-library/`, and
// handwritten TypeScript imports from there instead.
//
// The bridge re-exports the same runtime copy that Fable's own output imports,
// so runtime classes keep a single identity. The version is therefore read from
// the first-party generated imports rather than by picking a directory: stale
// `fable-library-ts.*` directories can survive an upgrade.
//
// This script runs as a post-fable step in scripts/Build.fsx.

open System.IO
open System.Text.RegularExpressions

type Command =
    | GenerateBridge
    | RunSelfTest

type BridgeError =
    | NoRuntimeImports
    | ConflictingVersions of versions: string list
    | RuntimeDirectoryMissing of path: string

type BridgeModule = { Name: string; HasDefaultExport: bool }

let bridgeDirectoryName = "fable-library"
let fableModulesDirectoryName = "fable_modules"
let runtimePackagePrefix = "fable-library-ts."

let runtimeImportPattern =
    Regex($"{fableModulesDirectoryName}/{Regex.Escape runtimePackagePrefix}([^/\"']+)/")

let defaultExportPattern = Regex(@"^export\s+default\b", RegexOptions.Multiline)

let parseArguments arguments =
    match arguments with
    | [] -> Ok GenerateBridge
    | [ "--self-test" ] -> Ok RunSelfTest
    | _ -> Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"

// Excludes Fable's package output and this script's own output, relative to
// src/generated.
let isFirstPartySource (relativePath: string) =
    let topDirectory = relativePath.Split(Path.DirectorySeparatorChar)[0]

    topDirectory <> fableModulesDirectoryName && topDirectory <> bridgeDirectoryName

let runtimeVersionsIn (source: string) =
    runtimeImportPattern.Matches(source) |> Seq.map _.Groups[1].Value |> Set.ofSeq

let resolveVersion versions =
    match versions |> Set.toList with
    | [] -> Error NoRuntimeImports
    | [ version ] -> Ok version
    | several -> Error(ConflictingVersions several)

let hasDefaultExport (source: string) = defaultExportPattern.IsMatch source

let renderBridge version bridgeModule =
    let specifier =
        $"../{fableModulesDirectoryName}/{runtimePackagePrefix}{version}/{bridgeModule.Name}.ts"

    [
        "// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit."
        $"export * from \"{specifier}\";"
        if bridgeModule.HasDefaultExport then
            $"export {{ default }} from \"{specifier}\";"
    ]
    |> List.map (fun line -> line + "\n")
    |> String.concat ""

let errorMessage error =
    match error with
    | NoRuntimeImports ->
        "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
    | ConflictingVersions versions ->
        let versionList = versions |> String.concat ", "

        $"ERROR: generated code imports several Fable runtime versions (%s{versionList}). Delete src/generated and run the Fable target again."
    | RuntimeDirectoryMissing path -> $"ERROR: Fable runtime directory %s{path} is missing."

// --- File-system operations, parameterized by root so the self-test can drive
// them against a temporary tree ---

let scanRuntimeVersions generatedRoot =
    Directory.EnumerateFiles(generatedRoot, "*.ts", SearchOption.AllDirectories)
    |> Seq.filter (fun path -> Path.GetRelativePath(generatedRoot, path) |> isFirstPartySource)
    |> Seq.map (File.ReadAllText >> runtimeVersionsIn)
    |> Set.unionMany

let runtimeDirectory generatedRoot version =
    let path =
        Path.Combine(generatedRoot, fableModulesDirectoryName, runtimePackagePrefix + version)

    if Directory.Exists path then
        Ok path
    else
        Error(RuntimeDirectoryMissing path)

let readBridgeModules runtimePath =
    Directory.EnumerateFiles(runtimePath, "*.ts", SearchOption.TopDirectoryOnly)
    |> Seq.map (fun path -> {
        Name = Path.GetFileNameWithoutExtension path
        HasDefaultExport = path |> File.ReadAllText |> hasDefaultExport
    })
    |> Seq.sortBy _.Name
    |> List.ofSeq

let writeBridge generatedRoot version bridgeModules =
    let bridgeRoot = Path.Combine(generatedRoot, bridgeDirectoryName)

    if Directory.Exists bridgeRoot then
        Directory.Delete(bridgeRoot, true)

    Directory.CreateDirectory bridgeRoot |> ignore

    for bridgeModule in bridgeModules do
        File.WriteAllText(Path.Combine(bridgeRoot, bridgeModule.Name + ".ts"), renderBridge version bridgeModule)

let generate generatedRoot =
    if not (Directory.Exists generatedRoot) then
        Error NoRuntimeImports
    else
        scanRuntimeVersions generatedRoot
        |> resolveVersion
        |> Result.bind (fun version ->
            runtimeDirectory generatedRoot version
            |> Result.map (fun runtimePath -> version, readBridgeModules runtimePath))

let runSelfTest () =
    let assertEqual name expected actual =
        if expected <> actual then
            failwith (sprintf "Self-test failed: %s. Expected %A, got %A." name expected actual)

    let usage = Error "Usage: GenerateFableLibraryBridge.fsx [--self-test]"
    assertEqual "no arguments generate the bridge" (Ok GenerateBridge) (parseArguments [])
    assertEqual "self-test arguments" (Ok RunSelfTest) (parseArguments [ "--self-test" ])
    assertEqual "unknown arguments fail" usage (parseArguments [ "--unknown" ])
    assertEqual "extra arguments fail" usage (parseArguments [ "--self-test"; "--self-test" ])

    assertEqual "first-party output is scanned" true (isFirstPartySource (Path.Combine("ViewModel", "Scene.ts")))

    assertEqual
        "Fable's package output is not scanned"
        false
        (isFirstPartySource (Path.Combine("fable_modules", "fable-library-ts.5.1.0", "List.ts")))

    assertEqual
        "the bridge's own output is not scanned"
        false
        (isFirstPartySource (Path.Combine("fable-library", "List.ts")))

    assertEqual
        "a first-party directory merely containing the bridge name is scanned"
        true
        (isFirstPartySource (Path.Combine("Persistence", "fable-library.ts")))

    let firstPartySource =
        """import { int32 } from "./fable_modules/fable-library-ts.5.1.0/Int32.ts";
import { Record } from "../fable_modules/fable-library-ts.5.1.0/Types.ts";
import { Decoder } from "./fable_modules/Thoth.Json.Core.0.9.1/Types.fs.ts";
"""

    assertEqual
        "runtime imports yield their version and other packages are ignored"
        (Set [ "5.1.0" ])
        (runtimeVersionsIn firstPartySource)

    assertEqual
        "pre-release versions are captured whole"
        (Set [ "5.0.0-rc.2" ])
        (runtimeVersionsIn """import { a } from "./fable_modules/fable-library-ts.5.0.0-rc.2/A.ts";""")

    assertEqual "a single version resolves" (Ok "5.1.0") (resolveVersion (Set [ "5.1.0" ]))
    assertEqual "no versions fail" (Error NoRuntimeImports) (resolveVersion Set.empty)

    assertEqual
        "several versions fail and are all reported"
        (Error(ConflictingVersions [ "5.1.0"; "5.20.0" ]))
        (resolveVersion (Set [ "5.20.0"; "5.1.0" ]))

    assertEqual "a default export is detected" true (hasDefaultExport "class A {}\nexport default A;\n")

    assertEqual "a default function export is detected" true (hasDefaultExport "export default function f() {}\n")

    assertEqual
        "named exports alone are not default exports"
        false
        (hasDefaultExport "export function f() {}\nexport const defaultValue = 1;\n")

    assertEqual "a commented-out default export is not detected" false (hasDefaultExport "// export default A;\n")

    assertEqual
        "a module without a default export re-exports its named exports"
        ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
         + "export * from \"../fable_modules/fable-library-ts.5.1.0/List.ts\";\n")
        (renderBridge "5.1.0" { Name = "List"; HasDefaultExport = false })

    assertEqual
        "a module with a default export also re-exports the default"
        ("// Generated by scripts/GenerateFableLibraryBridge.fsx. Do not edit.\n"
         + "export * from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n"
         + "export { default } from \"../fable_modules/fable-library-ts.5.20.0/Date.ts\";\n")
        (renderBridge "5.20.0" { Name = "Date"; HasDefaultExport = true })

    assertEqual
        "missing runtime imports explain how to recover"
        "ERROR: no Fable runtime imports found in src/generated. Run `npm run fake \"--\" --target Fable` first."
        (errorMessage NoRuntimeImports)

    assertEqual
        "conflicting versions are listed and explain how to recover"
        "ERROR: generated code imports several Fable runtime versions (5.1.0, 5.20.0). Delete src/generated and run the Fable target again."
        (errorMessage (ConflictingVersions [ "5.1.0"; "5.20.0" ]))

    assertEqual
        "a missing runtime directory is named"
        "ERROR: Fable runtime directory /missing/dir is missing."
        (errorMessage (RuntimeDirectoryMissing "/missing/dir"))

    let root =
        Path.Combine(Path.GetTempPath(), "fable-bridge-self-test-" + string (System.Guid.NewGuid()))

    let write relativePath (content: string) =
        let path = Path.Combine(Array.append [| root |] relativePath)
        Directory.CreateDirectory(Path.GetDirectoryName path) |> ignore
        File.WriteAllText(path, content)

    let runtimeImport version =
        $"import {{ a }} from \"./fable_modules/fable-library-ts.%s{version}/List.ts\";\n"

    try
        assertEqual "a missing generated root fails" (Error NoRuntimeImports) (generate root)

        write [| "Model.ts" |] "export const x = 1;\n"
        assertEqual "a tree without runtime imports fails" (Error NoRuntimeImports) (generate root)

        write [| "Model.ts" |] (runtimeImport "5.1.0")
        let missingRuntime = Path.Combine(root, "fable_modules", "fable-library-ts.5.1.0")

        assertEqual
            "an imported runtime directory that does not exist fails"
            (Error(RuntimeDirectoryMissing missingRuntime))
            (generate root)

        write [| "fable_modules"; "fable-library-ts.5.1.0"; "List.ts" |] "export function f() {}\n"
        write [| "fable_modules"; "fable-library-ts.5.1.0"; "Date.ts" |] "export default class D {}\n"
        write [| "fable_modules"; "fable-library-ts.5.1.0"; "lib"; "big.ts" |] "export default 1;\n"
        write [| "fable_modules"; "fable-library-ts.9.9.9"; "List.ts" |] "export function g() {}\n"
        write [| "fable_modules"; "fable-library-ts.5.1.0"; "Stale.ts" |] (runtimeImport "9.9.9")
        write [| "fable-library"; "Removed.ts" |] (runtimeImport "9.9.9")

        let expectedModules = [
            { Name = "Date"; HasDefaultExport = true }
            { Name = "List"; HasDefaultExport = false }
            { Name = "Stale"; HasDefaultExport = false }
        ]

        assertEqual
            "only first-party imports choose the version, and only top-level runtime modules are bridged"
            (Ok("5.1.0", expectedModules))
            (generate root)

        writeBridge root "5.1.0" expectedModules

        assertEqual
            "the bridge directory is recreated, removing stale modules"
            [ "Date.ts"; "List.ts"; "Stale.ts" ]
            (Directory.GetFiles(Path.Combine(root, "fable-library"))
             |> Array.map Path.GetFileName
             |> Array.sort
             |> List.ofArray)

        assertEqual
            "written bridges match the rendered contents"
            (renderBridge "5.1.0" { Name = "Date"; HasDefaultExport = true })
            (File.ReadAllText(Path.Combine(root, "fable-library", "Date.ts")))

        write [| "Other.ts" |] (runtimeImport "9.9.9")

        assertEqual
            "first-party imports of two versions fail"
            (Error(ConflictingVersions [ "5.1.0"; "9.9.9" ]))
            (generate root)
    finally
        if Directory.Exists root then
            Directory.Delete(root, true)

    printfn "Self-test: passed."

// --- Top-level I/O and control flow ---

let repoRoot = Path.GetDirectoryName(Path.GetFullPath(__SOURCE_DIRECTORY__))
let generatedRoot = Path.Combine(repoRoot, "src", "generated")

let scriptArgs = fsi.CommandLineArgs |> Array.skip 1

match parseArguments (scriptArgs |> Array.toList) with
| Error usage ->
    eprintfn "%s" usage
    exit 2
| Ok RunSelfTest -> runSelfTest ()
| Ok GenerateBridge ->
    match generate generatedRoot with
    | Error error ->
        eprintfn "%s" (errorMessage error)
        exit 1
    | Ok(version, bridgeModules) ->
        writeBridge generatedRoot version bridgeModules

        printfn
            $"GenerateFableLibraryBridge: wrote %d{bridgeModules.Length} bridge module(s) for fable-library-ts %s{version}."
